### PR TITLE
Setting up Eslint

### PR DESCRIPTION
**Pull request by renatonascalves**
* I'm setting ESlint, extending the airbnb one
* I'm removing some errors for now

The goal is to update the codebase to follow ESlint slowly.

PR related to #18

### CODE REVIEW

**Comment by imath** [comment]
Thanks a lot @renatonascalves for your PR about this. I was wondering: would it be possible to use the [wordpress/scripts](https://developer.wordpress.org/block-editor/packages/packages-scripts/) instead? I believe it would be better for a project like BuddyPress to do so.

**Comment by renatonascalves** [comment]
I had no idea that one existed! Let me investigate the link you provided and see how I can replace with that instead of what I have here.

:)

**Comment by imath** [comment]
Sure! Thanks for looking at it 😍

**Comment by Mamaduka** [comment]
If we just want ESLint config for the WP project I would recommend [`@wordpress/eslint-plugin`](https://www.npmjs.com/package/@wordpress/eslint-plugin).

**Pull request closed without merging**
